filepath = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
temp <- tempfile()
download.file(filepath,temp)
tab5rows <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, sep=";", nrows = 5)
classes <- sapply(tab5rows, class)
tabAll <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, colClasses = classes, sep=";", comment.char = "", na.strings = "?")
unlink(temp)
tabAll$Date <- as.Date(tabAll$Date, "%d/%m/%Y")
df <- subset(tabAll, Date == "2007-02-01" | Date == "2007-02-02")
df$Time <- strptime(paste(df$Date, as.character(df$Time)), "%Y-%m-%d %H:%M:%S")
plot(df$Time, df$Sub_metering_1, type='l', xlab='', ylab='Energy sub metering')
lines(df$Time, df$Sub_metering_2, type='l', col='red')
lines(df$Time, df$Sub_metering_3, type='l', col='blue')
legend("topright", lty = c(1, 1, 1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()
